version: "3.8"

services:
  queue:
    image: redis

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - coins_db_host=db
      - coins_db_name=coins_db
      - coins_db_user=foobar
      - coins_db_password=qwerty
      - coins_db_port=5432
    volumes:
      - "./initdb.sh:/docker-entrypoint-initdb.d/init_coins_db.sh:ro"

  webapp:
    image: webapp
    build:
      dockerfile: docker/Dockerfile
      context: ..
    depends_on:
      - db
      - queue
    environment:
      - deployment=production
      - coins_db_host=db
      - coins_db_name=coins_db
      - coins_db_user=foobar
      - coins_db_password=qwerty
      - coins_db_port=5432
      - alphavantage_api_key=$alphavantage_api_key
      - django_secret_key=$django_secret_key
    ports:
      - target: 8000
        published: 8000

  worker:
    image: worker
    build:
      dockerfile: docker/Dockerfile-worker
      context: ..
    depends_on:
      - db
      - queue
    environment:
      - deployment=production
      - DJANGO_SETTINGS_MODULE=coins.settings
      - coins_db_host=db
      - coins_db_name=coins_db
      - coins_db_user=foobar
      - coins_db_password=qwerty
      - coins_db_port=5432
      - alphavantage_api_key=$alphavantage_api_key
      - django_secret_key=$django_secret_key
  scheduler:
    image: scheduler
    build:
      dockerfile: docker/Dockerfile-scheduler
      context: ..
    depends_on:
      - queue
    environment:
      - deployment=production
      - DJANGO_SETTINGS_MODULE=coins.settings
      - coins_db_host=db
      - coins_db_name=coins_db
      - coins_db_user=foobar
      - coins_db_password=qwerty
      - coins_db_port=5432
      - alphavantage_api_key=$alphavantage_api_key
      - django_secret_key=$django_secret_key
