version: "3.8"

services:
  queue:
    image: redis

#  scheduler:
#    image: celery
#    depends_on:
#      - queue

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - coins_db_host=db
      - coins_db_name=coins_db
      - coins_db_user=foobar
      - coins_db_password=qwerty
      - coins_db_port=5432
    volumes:
      - "./initdb.sh:/docker-entrypoint-initdb.d/init_coins_db.sh:ro"

  webapp:
    image: webapp
    build:
      dockerfile: docker/Dockerfile
      context: ..
    depends_on:
      - db
      - queue
#      - scheduler
    environment:
      - deployment=production
      - coins_db_host=db
      - coins_db_name=coins_db
      - coins_db_user=foobar
      - coins_db_password=qwerty
      - coins_db_port=5432
    ports:
      - target: 8000
        published: 8000
    volumes:
#      - type: bind
#        source: ..
#        target: /srv/coins

#  worker:
#    image: worker
#    build:
#      dockerfile: docker/Dockerfile-worker
#      context: ..
#    depends_on:
#      - db
#      - queue
#      - scheduler
#    environment:
#      - deployment=production
#      - coins_db_host=db
#      - coins_db_name=coins_db
#      - coins_db_user=foobar
#      - coins_db_password=qwerty
#      - coins_db_port=5432
#    volumes:
#      - type: bind
#        source: ..
#        target: /srv/coins
#

