# Generated by Django 4.0.1 on 2022-02-01 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_currency",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                    ),
                ),
                (
                    "to_currency",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=2)
                        ],
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("alphavantage_timestamp", models.DateTimeField()),
                ("rate", models.FloatField()),
                ("bid_price", models.FloatField()),
                ("ask_price", models.FloatField()),
            ],
            options={
                "ordering": ["-timestamp", "-alphavantage_timestamp"],
            },
        ),
    ]
